epochs: 200
output_dir: output_dir

model:
  name: PastaGANModel
  latent_dim: &LATENT_DIM 16
  lambda_sty: 1
  lambda_ds: 2
  lambda_cyc: 1
  synthesis:
    name: SynthesisNetwork
    w_dim: &W_DIM 512
    img_resolution: &IMAGE_SIZE 256
    img_channels: &IMG_CHANNELS 3
    channel_base: &CHANNEL_BASE 16384
    channel_max: &CHANNEL_MAX 512
    num_fp16_res: &NUM_FP16_RES 3
    conv_clamp: &CONV_CLAMP 256
    use_noise: true
  mapping:
    name: MappingNetwork
    z_dim: &Z_DIM 0
    c_dim: &C_DIM 512
    w_dim: *W_DIM
    num_ws: 14
    num_layers: 1
  const_encoding:
    name: ConstEncoderNetwork
    input_nc: 6
    output_nc: &OC 512
    ngf: &NGF 64
    n_downsampling: &N_DOWN 6
  style_encoding:
    name: StyleEncoderNetwork
    input_nc: 60
    output_nc: *OC
    ngf: *NGF
    n_downsampling: *N_DOWN
  discriminator:
    name: PastaGANDiscriminator
    c_dim: *C_DIM
    img_resolution: *IMAGE_SIZE
    img_channels: *IMG_CHANNELS
    channel_base: *CHANNEL_BASE
    channel_max: *CHANNEL_MAX
    num_fp16_res: *NUM_FP16_RES
    conv_clamp: *CONV_CLAMP
    block_kwargs: {}
    mapping_kwargs: {}
    epilogue_kwargs: {mbstd_group_size: 4}

dataset:
  train:
    name: PastaGANDataset
    dataroot: ../UPT_256_192_my2/Zalando_256_192
    txt_name: train_pairs_front_list_0508.txt
    is_train: True
    use_labels: true
    xflip: False
    num_workers: 0
    batch_size: 2
    test_count: -1
    preprocess: None

  test:
#    name: PastaGANDataset
#    dataroot: ../UPT_256_192_my2/Zalando_256_192
#    txt_name: train_pairs_front_list_0508.txt
#    is_train: True
#    use_labels: true
#    xflip: False
#    num_workers: 0
#    batch_size: 2
#    test_count: -1
#    preprocess: None
    name: PastaGANDataset
    dataroot: ../UPT_256_192_my2/Zalando_256_192
    txt_name: test_pairs_front_list_shuffle_0508.txt
    is_train: False
    use_labels: true
    xflip: False
    num_workers: 0
    batch_size: 1
    test_count: 16
    preprocess: None

lr_scheduler:
  name: LinearDecay
  learning_rate: 0.0001
  start_epoch: 100
  decay_epochs: 100
  # will get from real dataset
  iters_per_epoch: 365

optimizer:
  synthesis:
    name: Adam
    net_names:
      - synthesis
    beta1: 0.0
    beta2: 0.99
    weight_decay: 0.0001
  mapping:
    name: Adam
    net_names:
      - mapping
    beta1: 0.0
    beta2: 0.99
    weight_decay: 0.0001
  const_encoding:
    name: Adam
    net_names:
      - const_encoding
    beta1: 0.0
    beta2: 0.99
    weight_decay: 0.0001
  style_encoding:
    name: Adam
    net_names:
      - style_encoding
    beta1: 0.0
    beta2: 0.99
    weight_decay: 0.0001
  discriminator:
    name: Adam
    net_names:
      - discriminator
    beta1: 0.0
    beta2: 0.99
    weight_decay: 0.0001

validate:
  interval: 3000
  save_img: true

log_config:
  interval: 20
  visiual_interval: 3000

snapshot_config:
  interval: 5
