epochs: 200
output_dir: output_dir

model:
  name: StyleGANv2ADAModel
  G_reg_interval: 4
  D_reg_interval: 16
  # loss
  r1_gamma: 0.5
  synthesis:
    name: StyleGANv2ADA_SynthesisNetwork
    w_dim: &W_DIM 512
    img_resolution: &IMAGE_SIZE 512
    img_channels: &IMG_CHANNELS 3
    channel_base: &CHANNEL_BASE 32768
    channel_max: &CHANNEL_MAX 512
    num_fp16_res: &NUM_FP16_RES 4
    conv_clamp: &CONV_CLAMP 256
  mapping:
    name: StyleGANv2ADA_MappingNetwork
    z_dim: &Z_DIM 512
    c_dim: &C_DIM 0
    w_dim: *W_DIM
    num_ws: 16
    num_layers: 8
  discriminator:
    name: StyleGANv2ADA_Discriminator
    c_dim: *C_DIM
    img_resolution: *IMAGE_SIZE
    img_channels: *IMG_CHANNELS
    channel_base: *CHANNEL_BASE
    channel_max: *CHANNEL_MAX
    num_fp16_res: *NUM_FP16_RES
    conv_clamp: *CONV_CLAMP
    block_kwargs: {}
    mapping_kwargs: {}
    epilogue_kwargs: {mbstd_group_size: 8}

dataset:
  train:
    name: StyleGANv2ADADataset
    dataroot: ../data/data42681/afhq/train/cat
    is_train: True
    resolution: *IMAGE_SIZE
    use_labels: False
    xflip: False
    num_workers: 0
    batch_size: 2
    len_phases: 4
    preprocess: None

  test:
    name: StyleGANv2ADADataset
    dataroot: ../data/data42681/afhq/train/cat
    is_train: False
    resolution: *IMAGE_SIZE
    use_labels: False
    xflip: False
    num_workers: 0
    batch_size: 1
    len_phases: 4
    preprocess: None

lr_scheduler_G:
  name: LinearDecay
  learning_rate: 0.0025
  start_epoch: 100
  decay_epochs: 100
  # will get from real dataset
  iters_per_epoch: 365

lr_scheduler_D:
  name: LinearDecay
  learning_rate: 0.0025
  start_epoch: 100
  decay_epochs: 100
  # will get from real dataset
  iters_per_epoch: 365

optimizer:
  generator:
    name: Adam
    net_names:
      - synthesis
      - mapping
    beta1: 0.0
    beta2: 0.99
    epsilon: 1e-8
  discriminator:
    name: Adam
    net_names:
      - discriminator
    beta1: 0.0
    beta2: 0.99
    epsilon: 1e-8

validate:
  interval: 175   # test iters
  save_img: true

log_config:
  interval: 10   # log iters
  visiual_interval: 175   # visual iters

snapshot_config:
  interval: 1   # save epochs
